name: "My action"
description: "Test my action"

inputs:
  message:
    description: "message to print"
    required: true
    default: "Hola"

runs:
  using: "composite"

  steps: 
  - name: Hola mundo
    run: echo "hola ${{inputs.message}}" 
    shell: bash